"""Generate a Markdown scan report and write it to a file or stdout."""

from __future__ import annotations

import sys
from datetime import datetime
from typing import Optional

from tokenleak.db.base import AlertRow, Database, ScanRow


def _severity_emoji(severity: str) -> str:
    return {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🔵"}.get(severity, "⚪")


def generate(db: Database, scan_id: int, repo_url: str) -> str:
    scan_rows = db.list_scans()
    scan = next((s for s in scan_rows if s.id == scan_id), None)
    alerts = db.list_alerts(scan_id)
    notes = db.list_notes(scan_id)

    lines = [
        f"# TokenLeak Report",
        f"",
        f"**Repository:** `{repo_url}`",
        f"**Scan ID:** {scan_id}",
        f"**Commit:** `{scan.commit_sha[:12] if scan else 'N/A'}`",
        f"**Started:** {scan.scan_started_at or 'N/A'}",
        f"**Finished:** {scan.scan_finished_at or 'N/A'}",
        f"**Status:** {scan.status if scan else 'N/A'}",
        f"**Tokens used:** {scan.tokens_used:,}" if scan else "",
        f"",
        f"---",
        f"",
    ]

    # ── Summary ────────────────────────────────────────────────────────────────
    if alerts:
        severity_counts: dict[str, int] = {}
        for a in alerts:
            severity_counts[a.severity or "unknown"] = severity_counts.get(a.severity or "unknown", 0) + 1

        lines += [
            f"## Summary: {len(alerts)} alert(s) found",
            "",
        ]
        for sev in ["critical", "high", "medium", "low", "unknown"]:
            c = severity_counts.get(sev, 0)
            if c:
                lines.append(f"- {_severity_emoji(sev)} **{sev.upper()}**: {c}")
        lines.append("")
    else:
        lines += ["## Summary: No alerts found", ""]

    # ── Alerts ─────────────────────────────────────────────────────────────────
    if alerts:
        lines.append("## Alerts")
        lines.append("")
        for idx, alert in enumerate(alerts, start=1):
            aj = alert.agent_json or {}
            lines += [
                f"### [{idx}] {_severity_emoji(alert.severity)} {(alert.alert_type or '?').upper()} — `{alert.file_path}`",
                f"",
                f"**Severity:** {alert.severity}  ",
                f"**Lines:** {alert.line_start}–{alert.line_end}  ",
                f"",
                f"**Description:** {aj.get('description', 'N/A')}",
                f"",
            ]
            if aj.get("code_snippet"):
                lines += [
                    f"**Snippet:**",
                    f"```",
                    aj["code_snippet"][:1000],
                    f"```",
                    f"",
                ]
            if aj.get("how_used"):
                lines.append(f"**How used:** {aj['how_used']}")
                lines.append("")
            if aj.get("confirmation"):
                lines.append(f"**Confirmation:** {aj['confirmation']}")
                lines.append("")
            lines.append("---")
            lines.append("")

    # ── Notes ──────────────────────────────────────────────────────────────────
    if notes:
        lines += ["## Agent Notes", ""]
        for i, note in enumerate(notes, start=1):
            lines += [f"### Note {i}", "", note, ""]

    lines += [
        f"---",
        f"*Generated by TokenLeak at {datetime.utcnow().isoformat()}Z*",
    ]
    return "\n".join(lines)


def write_report(content: str, output: Optional[str]) -> None:
    """Write report to file path, or '-' for stdout."""
    if output is None:
        return
    if output == "-":
        sys.stdout.write(content + "\n")
    else:
        with open(output, "w", encoding="utf-8") as f:
            f.write(content + "\n")
